const axios = require('axios');
const { downloadContentFromMessage } = require('@whiskeysockets/baileys');
const { cmd } = require('../command');
const FormData = require('form-data');

cmd({
    pattern: "nano",
    alias: ["banana", "nanobanana"],
    react: "🍌",
    desc: "Generate/transform image using Nano Banana AI",
    category: "image",
    use: ".nano <prompt> (reply to image)",
    filename: __filename,
},
async (conn, mek, m, { from, quoted, body, reply }) => {
    try {
        // Must reply to an image
        if (!quoted || !quoted.imageMessage) {
            return reply("🖼️ Please reply to an image with `.nano <your prompt>`");
        }

        // Extract prompt from command (text after .nano)
        const prompt = body.split(' ').slice(1).join(' ').trim();
        if (!prompt) {
            return reply("✏️ Please provide a prompt.\nExample: `.nano make this a cartoon`");
        }

        await reply("⏳ Nano Banana is working on your image, please wait...");

        // Download image from WhatsApp
        const stream = await downloadContentFromMessage(
            quoted.imageMessage,
            'image'
        );
        let buffer = Buffer.from([]);
        for await (const chunk of stream) {
            buffer = Buffer.concat([buffer, chunk]);
        }

        // Upload image to temporary hosting
        const form = new FormData();
        form.append('file', buffer, {
            filename: 'nano.jpg',
            contentType: 'image/jpeg'
        });

        const uploadRes = await axios.post(
            'https://tmpfiles.org/api/v1/upload',
            form,
            { headers: form.getHeaders() }
        );

        const imageUrl = uploadRes.data.data.url.replace(
            'tmpfiles.org/',
            'tmpfiles.org/dl/'
        );

        // Step 3: Call Nano Banana API
        // ✅ Correct param is 'url' — API returns raw image binary directly (not JSON)
        const apiUrl = `https://api-faa.my.id/faa/nano-banana?url=${encodeURIComponent(imageUrl)}&prompt=${encodeURIComponent(prompt)}`;

        const apiRes = await axios.get(apiUrl, {
            timeout: 120000,
            responseType: 'arraybuffer' // ✅ Raw image binary response
        });

        // Step 4: Convert response to buffer
        const resultBuffer = Buffer.from(apiRes.data);

        if (!resultBuffer || resultBuffer.length < 100) {
            return reply("❌ Nano Banana returned an empty image. Please try again.");
        }

        // Step 5: Send image buffer directly to WhatsApp
        await conn.sendMessage(
            from,
            {
                image: resultBuffer,
                caption: `> 🍌 *Nano Banana Result*\n> 📝 Prompt: ${prompt}\n> ✨ Generated by 𝐑𝐔𝐇𝐈𝐈𝐈😻🎀💗`
            },
            { quoted: m }
        );

    } catch (err) {
        console.error("NANO BANANA ERROR:", err.message || err);
        reply("❌ Nano Banana failed. Please try again later.");
    }
});
